// enum FLAG_ENTITY_TYPE { USER, TEXT, PORTFOLIO }
// enum FLAG_REASON_TYPE {
//   HARASSMENT,
//   INAPPROPRIATE,
//   OTHER,
//   SCAM,
//   SPAM,
//   SELF_PROMO
// }
// enum REVIEW_STATUS {
//   NO_ACTION,
//   PENDING,
//   DELETED,
//   AUTO_DELETED,
//   IN_PROGRESS,
//   SUSPENDED
// }
