enum LOADING_STATUS { LOADING, NOT_LOADING }

enum API_STATUS { NOT_STARTED, PENDING, FINISHED, ERROR, EMPTY }

enum SELECT_ITEM_MENU { EDIT, DELETE, CANCEL }

enum NEW_GROUP_CHAT_STATUS { NEW, PARTICIPANTS, CREATE }
