name: iris_common
description: A new Flutter package project.
version: 0.0.127+126
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependency_overrides:
  web_socket_channel:
    git:
      url: https://github.com/jonataslaw/web_socket_channel

# the package country code picker uses this dependency, but it appears to be abandoned
# and is not compatible with flutter 3
  modal_bottom_sheet: ^2.0.1


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.3
  flutter_svg: ^1.0.3
  graphql: 5.0.0-nullsafety.4
  collection: ^1.16.0
  flutter_secure_storage: ^5.0.2
  package_info_plus: ^1.0.4
  simple_moment: ^1.0.4
  flutter_cache_manager: ^3.3.0
  jwt_decode: ^0.3.1
  flutter_dotenv: ^5.0.2
  flutter_feather_icons: ^2.0.0
  firebase_messaging: ^11.2.3
  firebase_core: ^1.10.5
  contacts_service: ^0.6.0
  local_auth: ^2.0.2
  flutter_inappwebview: ^5.2.1+1
  syncfusion_flutter_core: ^20.1.55
  url_launcher: ^6.0.3
  posthog_flutter: ^2.0.0
  image_cropper: ^2.0.2
  permission_handler: ^9.2.0
  html: ^0.15.0
  shimmer: ^2.0.0-nullsafety.0
  unicons: ^2.0.1
  image_picker: ^0.8.4
  connectivity_plus: ^2.0.3
  firebase_dynamic_links: ^4.0.2
  device_info: ^2.0.0
  cached_network_image: ^3.2.1
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_form_builder: ^7.0.0
  throttling: ^1.0.0
  enum_to_string: ^2.0.1
  flutter_slidable: ^1.1.0
  flutter_screenutil: ^5.5.2
  carousel_slider: ^4.0.0
  form_builder_validators: ^8.1.1
  share_plus: ^4.0.4
  country_code_picker: ^2.0.1
  flutter_libphonenumber: ^1.2.2
  photo_view: ^0.14.0
  flutter_email_sender: ^5.0.0
  video_player: ^2.2.5
  visibility_detector: ^0.3.3
  provider:
  # extended_text: ^8.0.2
  timeago: ^3.1.0
  # extended_text_field: ^9.0.3
  extended_text_library: ^9.1.0
  flutter_spinkit: ^5.0.0
  freezed_annotation:
  json_annotation:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner:
  freezed:
  json_serializable: ^6.1.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages